# Generated by Django 3.1.3 on 2021-10-30 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companys', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github', models.URLField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True, max_length=254)),
                ('portfolio_site', models.URLField(blank=True, max_length=254)),
                ('resume', models.FileField(upload_to='resume/')),
                ('tell_us_something_about_yourself', models.TextField(max_length=150)),
                ('tell_us_about_your_weaknesses', models.TextField(max_length=150)),
                ('apart_from_core_technical_skills', models.TextField(max_length=150)),
                ('how_do_you_handle_stress_and_Pressure', models.TextField(max_length=150)),
                ('do_you_like_to_work_in_a_team_or_work_alone', models.CharField(max_length=50)),
                ('What_do_you_prefer_on_weekends_staying_home_or_going_out', models.CharField(max_length=50)),
                ('would_you_correct_your_colleagues_or_wont_bother', models.CharField(max_length=50)),
                ('in_a_group_whichin_a_group_which_person_has_your_attention', models.CharField(max_length=50)),
                ('do_you_believe_you_can_achieve_everything', models.CharField(max_length=50)),
                ('What_attracts_you_science_or_music', models.CharField(max_length=50)),
                ('do_you_like_to_plan_before_or_after_things', models.CharField(max_length=50)),
                ('would_you_change_your_preferences', models.CharField(max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companys.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
